#pragma once

// Get semantic version from menuconfig
#define FW_VERSION_MAJOR CONFIG_FIRMWARE_VERSION_MAJOR
#define FW_VERSION_MINOR CONFIG_FIRMWARE_VERSION_MINOR
#define FW_VERSION_PATCH CONFIG_FIRMWARE_VERSION_PATCH

#define STRINGIFY(x) STRINGIFY2(x)
#define STRINGIFY2(x) #x

#define FW_VERSION_SEMANTIC \
    STRINGIFY(FW_VERSION_MAJOR) "." STRINGIFY(FW_VERSION_MINOR) "." STRINGIFY(FW_VERSION_PATCH)

// Git version string (injected via CMake)
#ifndef FW_GIT_VERSION
#define FW_GIT_VERSION "unknown"
#endif

#define FW_VERSION_FULL FW_VERSION_SEMANTIC " (" FW_GIT_VERSION ")"